// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFRpi9BMf8M_SY4KGzMULc4948DDV35oE',
    appId: '1:503211862066:web:917f135ac0d36ca276b42b',
    messagingSenderId: '503211862066',
    projectId: 'cmru-peesonnong-flutter',
    authDomain: 'cmru-peesonnong-flutter.firebaseapp.com',
    storageBucket: 'cmru-peesonnong-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6RDcspuqZN-dlrjWvWlZqIlu6dd8jsdk',
    appId: '1:503211862066:android:7c09dfba5c66bd3976b42b',
    messagingSenderId: '503211862066',
    projectId: 'cmru-peesonnong-flutter',
    storageBucket: 'cmru-peesonnong-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD60B4oKYUCCc4u6Lagm27z3hcGVQ1gitY',
    appId: '1:503211862066:ios:6a86ae6e9c2670a376b42b',
    messagingSenderId: '503211862066',
    projectId: 'cmru-peesonnong-flutter',
    storageBucket: 'cmru-peesonnong-flutter.firebasestorage.app',
    iosBundleId: 'com.example.todoGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD60B4oKYUCCc4u6Lagm27z3hcGVQ1gitY',
    appId: '1:503211862066:ios:6a86ae6e9c2670a376b42b',
    messagingSenderId: '503211862066',
    projectId: 'cmru-peesonnong-flutter',
    storageBucket: 'cmru-peesonnong-flutter.firebasestorage.app',
    iosBundleId: 'com.example.todoGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFRpi9BMf8M_SY4KGzMULc4948DDV35oE',
    appId: '1:503211862066:web:74c4a53c3f31bee876b42b',
    messagingSenderId: '503211862066',
    projectId: 'cmru-peesonnong-flutter',
    authDomain: 'cmru-peesonnong-flutter.firebaseapp.com',
    storageBucket: 'cmru-peesonnong-flutter.firebasestorage.app',
  );
}
